sudo: required
dist: trusty
language: c
compiler:
  - gcc
env:
  - KVER=3.2.1
  - KVER=3.16.1
  - KVER=3.2.1 FRIB=YES
  - KVER=3.16.1 FRIB=YES
install:
  - install -d $HOME/linux
  - curl -s https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-$KVER.tar.xz | tar -C $HOME/linux --strip-components=1 -xJ
  - make -C $HOME/linux defconfig
  - make -C $HOME/linux modules_prepare
script:
  - if [ "$FRIB" = YES ] ; then cp config.example .config; fi
  - if [ "$FRIB" != YES ] ; then cp config.bare .config; fi
  - make KERNELDIR=$HOME/linux
