sudo: required
dist: trusty
language: c
compiler:
  - gcc
env:
  - KVER=3.2.1
  - KVER=3.16.1
install:
  - install -d $HOME/linux
  - curl -s https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-$KVER.tar.xz | tar -C $HOME/linux --strip-components=1 -xJ
  - make -C $HOME/linux defconfig
  - make -C $HOME/linux modules_prepare
script:
  - cp config.example .config
  - make KERNELDIR=$HOME/linux
