#!/bin/sh

NAME=MODULE_NAME
VERSION=MODULE_VERSION

set -e

udev_rule_remove () {
  rm -f /etc/udev/rules.d/10-CAENels-AMC-Pico.rules
}

etc_modules_remove () {
  sed -i '/amc_pico/d' /etc/modules
}

case "$1" in
    remove|upgrade|deconfigure)
      if [  "`dkms status -m $NAME`" ]; then
         udev_rule_remove
         etc_modules_remove
         dkms remove -m $NAME -v $VERSION --all
      fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


